import type {
  ActivityLog,
  ClientProfile,
  InvoiceRecord,
  PaymentGatewayConfig,
  PaymentTransaction,
  Service,
  ServiceShowcase,
  TeamMember,
} from './types'

export const ORGANIZATION = {
  legalName: 'Aurora Digital Solutions Pvt. Ltd.',
  displayName: 'Aurora Digital Solutions',
  tagline: 'Strategic Digital Expertise Delivered',
  taxRegistration: 'GSTIN: 27AABCU9603R1Z7',
  address: {
    line1: '7th Floor, Crest Tower',
    line2: 'Bandra Kurla Complex',
    city: 'Mumbai',
    state: 'Maharashtra',
    postalCode: '400051',
    country: 'India',
  },
  contact: {
    phone: '+91 22 4150 2380',
    email: 'billing@auroradigital.in',
    website: 'www.auroradigital.in',
  },
  bank: {
    beneficiary: 'Aurora Digital Solutions Pvt. Ltd.',
    bankName: 'Horizon Bank of India',
    accountNumber: '018901290384',
    ifsc: 'HRZN0001290',
    swift: 'HRZNINBB',
  },
}

export const SERVICE_CATALOG: Service[] = [
  {
    id: 'svc-dm-001',
    name: 'Search Engine Optimization Retainer',
    category: 'Digital Marketing',
    description:
      'Monthly optimization of on-page, off-page, and technical SEO assets with reporting and analytics.',
    unit: 'Monthly Retainer',
    unitRate: 65000,
  },
  {
    id: 'svc-dm-002',
    name: 'Social Media Campaign Management',
    category: 'Digital Marketing',
    description:
      'End-to-end campaign management across social platforms including creative production and performance tracking.',
    unit: 'Campaign',
    unitRate: 54000,
  },
  {
    id: 'svc-web-001',
    name: 'Corporate Website Redesign',
    category: 'Web Development',
    description:
      'Responsive redesign with UX strategy, CMS integration, QA, and deployment.',
    unit: 'Project',
    unitRate: 185000,
  },
  {
    id: 'svc-web-002',
    name: 'eCommerce Platform Build',
    category: 'Web Development',
    description:
      'Full-stack eCommerce implementation with payment gateway integration and admin training.',
    unit: 'Project',
    unitRate: 275000,
  },
  {
    id: 'svc-soft-001',
    name: 'Custom CRM Module Development',
    category: 'Software Development',
    description:
      'Build and integrate tailored CRM module with existing enterprise systems.',
    unit: 'Sprint',
    unitRate: 95000,
  },
  {
    id: 'svc-soft-002',
    name: 'Enterprise API Integration Suite',
    category: 'Software Development',
    description:
      'Secure API integration including documentation, testing, and deployment support.',
    unit: 'Integration Package',
    unitRate: 132000,
  },
]

export const SERVICE_SHOWCASES: ServiceShowcase[] = [
  {
    id: 'svc-feat-001',
    headline: 'Retainer playbook: Digital growth command centre',
    summary:
      'A quarterly program combining SEO, performance media, and marketing automation to deliver measurable pipeline lift for BFSI clients.',
    deliverables: ['SEO sprints', 'Performance media ops', 'Monthly CX analytics', 'Executive scorecards'],
    persona: 'Marketing Directors • BFSI',
    projectedTimeline: '12-week onboarding • then monthly cadence',
  },
  {
    id: 'svc-feat-002',
    headline: 'Commerce accelerator: High-converting eCommerce relaunch',
    summary:
      'Full-stack rebuild of customer journeys, integrating Razorpay Enterprise and headless CMS for omnichannel retail brands.',
    deliverables: ['UX journey remap', 'Headless storefront', 'Payment orchestration', 'Post-launch CRO roadmap'],
    persona: 'VP Digital • Retail & D2C',
    projectedTimeline: '16-week transformation sprint',
  },
  {
    id: 'svc-feat-003',
    headline: 'Operations automation: Logistics API command suite',
    summary:
      'Microservice architecture to consolidate warehouse, transport and finance signals with real-time reconciliation dashboards.',
    deliverables: ['Integration blueprint', 'Custom middleware', 'Invoice automation', '24/7 observability'],
    persona: 'COO • Logistics & Supply Chain',
    projectedTimeline: 'Discovery + 3 agile increments',
  },
]

export const PAYMENT_GATEWAY: PaymentGatewayConfig = {
  id: 'pg-razor-001',
  providerName: 'Razorpay Enterprise',
  status: 'Active',
  reconciliationStatus: 'On schedule',
  settlementWindow: 'T+1 business day',
  feePercentage: 1.9,
  lastSync: '2025-06-12T09:20:00+05:30',
  credentials: {
    merchantId: 'MERCH-ADS-1290',
    keyEnding: '89F2',
    webhookUrl: 'https://auroradigital.in/api/payments/webhook',
  },
  channels: [
    {
      id: 'pg-ch-upi',
      label: 'Unified Payments (UPI)',
      method: 'UPI',
      status: 'Enabled',
      successRate: 98.4,
      slaMinutes: 5,
    },
    {
      id: 'pg-ch-card',
      label: 'Corporate Cards',
      method: 'Credit Card',
      status: 'Enabled',
      successRate: 95.8,
      slaMinutes: 8,
    },
    {
      id: 'pg-ch-net',
      label: 'Net Banking',
      method: 'NetBanking',
      status: 'Degraded',
      successRate: 87.5,
      slaMinutes: 25,
    },
    {
      id: 'pg-ch-wire',
      label: 'International Wire',
      method: 'Wire Transfer',
      status: 'Enabled',
      successRate: 99.1,
      slaMinutes: 180,
    },
  ],
}

export const PAYMENT_TRANSACTIONS: PaymentTransaction[] = [
  {
    id: 'txn-88421',
    invoiceId: 'inv-003',
    clientId: 'cl-aurora-003',
    amount: 198500,
    currency: 'INR',
    method: 'UPI',
    status: 'Succeeded',
    receivedAt: '2025-06-11T16:55:00+05:30',
    feeAmount: 3771.5,
    netAmount: 194728.5,
    reference: 'UTR2025A9912',
  },
  {
    id: 'txn-88422',
    invoiceId: 'inv-001',
    clientId: 'cl-aurora-001',
    amount: 215000,
    currency: 'INR',
    method: 'Credit Card',
    status: 'Pending',
    receivedAt: '2025-06-12T08:40:00+05:30',
    feeAmount: 4085,
    netAmount: 210915,
    reference: 'CCPAY543218',
  },
  {
    id: 'txn-88423',
    invoiceId: 'inv-002',
    clientId: 'cl-aurora-002',
    amount: 275000,
    currency: 'INR',
    method: 'NetBanking',
    status: 'Failed',
    receivedAt: '2025-06-10T10:05:00+05:30',
    feeAmount: 0,
    netAmount: 0,
    reference: 'NBNK768912',
  },
  {
    id: 'txn-88424',
    invoiceId: 'inv-005',
    clientId: 'cl-aurora-001',
    amount: 65000,
    currency: 'INR',
    method: 'UPI',
    status: 'Succeeded',
    receivedAt: '2025-04-08T12:25:00+05:30',
    feeAmount: 1235,
    netAmount: 63765,
    reference: 'UTR2025B4421',
  },
]

export const INVOICE_LEDGER: InvoiceRecord[] = [
  {
    id: 'inv-001',
    invoiceNumber: 'ADS-2025-043',
    clientId: 'cl-aurora-001',
    engagement: 'Digital Growth Retainer',
    currency: 'INR',
    amount: 215000,
    status: 'Pending',
    issueDate: '2025-06-02',
    dueDate: '2025-06-17',
    lastUpdated: '2025-06-05',
  },
  {
    id: 'inv-002',
    invoiceNumber: 'ADS-2025-041',
    clientId: 'cl-aurora-002',
    engagement: 'eCommerce Revamp Sprint 2',
    currency: 'INR',
    amount: 275000,
    status: 'Overdue',
    issueDate: '2025-05-10',
    dueDate: '2025-05-25',
    lastUpdated: '2025-06-10',
  },
  {
    id: 'inv-003',
    invoiceNumber: 'ADS-2025-039',
    clientId: 'cl-aurora-003',
    engagement: 'Warehouse Ops Automation',
    currency: 'INR',
    amount: 198500,
    status: 'Paid',
    issueDate: '2025-04-28',
    dueDate: '2025-05-12',
    lastUpdated: '2025-05-09',
  },
  {
    id: 'inv-004',
    invoiceNumber: 'ADS-2025-034',
    clientId: 'cl-aurora-002',
    engagement: 'Social Media Campaign Q2',
    currency: 'INR',
    amount: 86000,
    status: 'Paid',
    issueDate: '2025-04-01',
    dueDate: '2025-04-16',
    lastUpdated: '2025-04-13',
  },
  {
    id: 'inv-005',
    invoiceNumber: 'ADS-2025-029',
    clientId: 'cl-aurora-001',
    engagement: 'SEO Retainer - April',
    currency: 'INR',
    amount: 65000,
    status: 'Paid',
    issueDate: '2025-03-31',
    dueDate: '2025-04-15',
    lastUpdated: '2025-04-10',
  },
  {
    id: 'inv-006',
    invoiceNumber: 'ADS-2025-045',
    clientId: 'cl-aurora-003',
    engagement: 'API Integration Support',
    currency: 'INR',
    amount: 132000,
    status: 'Draft',
    issueDate: '2025-06-12',
    dueDate: '2025-06-27',
    lastUpdated: '2025-06-12',
  },
]

export const ACTIVITY_LOG: ActivityLog[] = [
  {
    id: 'act-001',
    timestamp: '2025-06-12T09:45:00+05:30',
    summary: 'Invoice ADS-2025-045 saved as draft by Priya Shah',
    actor: 'Priya Shah',
    activityType: 'invoice',
    relatedInvoiceId: 'inv-006',
  },
  {
    id: 'act-002',
    timestamp: '2025-06-11T17:10:00+05:30',
    summary: 'Payment of ₹1,98,500 received for ADS-2025-039',
    actor: 'Auto-Reconcile Bot',
    activityType: 'payment',
    relatedInvoiceId: 'inv-003',
  },
  {
    id: 'act-003',
    timestamp: '2025-06-10T11:05:00+05:30',
    summary: 'Reminder email sent to Helios Retail for overdue invoice',
    actor: 'Collections Suite',
    activityType: 'reminder',
    relatedInvoiceId: 'inv-002',
  },
  {
    id: 'act-004',
    timestamp: '2025-06-08T15:20:00+05:30',
    summary: 'Internal note added about Nimbus Finserve contract renewal',
    actor: 'Karan Patel',
    activityType: 'note',
  },
]

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-01',
    name: 'Priya Shah',
    role: 'Finance Lead',
    email: 'priya.shah@auroradigital.in',
    avatarColor: '#7F5AF0',
    initials: 'PS',
  },
  {
    id: 'tm-02',
    name: 'Karan Patel',
    role: 'Account Strategist',
    email: 'karan.patel@auroradigital.in',
    avatarColor: '#00A896',
    initials: 'KP',
  },
  {
    id: 'tm-03',
    name: 'Megha Rao',
    role: 'Collections Specialist',
    email: 'megha.rao@auroradigital.in',
    avatarColor: '#EF8354',
    initials: 'MR',
  },
  {
    id: 'tm-04',
    name: 'Arjun Desai',
    role: 'Delivery Director',
    email: 'arjun.desai@auroradigital.in',
    avatarColor: '#355070',
    initials: 'AD',
  },
]

export const CLIENT_DIRECTORY: ClientProfile[] = [
  {
    id: 'cl-aurora-001',
    companyName: 'Nimbus Finserve Ltd.',
    contactName: 'Riya Malhotra',
    email: 'riya.malhotra@nimbusfinserve.com',
    phone: '+91 98190 44221',
    addressLine1: '903, Sapphire Heights',
    addressLine2: 'Andheri West',
    city: 'Mumbai',
    state: 'Maharashtra',
    postalCode: '400058',
    country: 'India',
    gstin: '27AACCN1234B1Z9',
  },
  {
    id: 'cl-aurora-002',
    companyName: 'Helios Retail Pvt. Ltd.',
    contactName: 'Ashwin Rao',
    email: 'ashwin.rao@heliosretail.in',
    phone: '+91 99876 55210',
    addressLine1: '2nd Floor, Meridian Plaza',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCode: '560001',
    country: 'India',
    gstin: '29AAECP3245L1Z3',
  },
  {
    id: 'cl-aurora-003',
    companyName: 'Orbit Logistics & Warehousing LLP',
    contactName: 'Samarjeet Singh',
    email: 'samarjeet@orbitlogistics.com',
    phone: '+91 97173 77660',
    addressLine1: 'Plot No. 18, Sector 62',
    city: 'Noida',
    state: 'Uttar Pradesh',
    postalCode: '201309',
    country: 'India',
    gstin: '09AAHFO6521K1ZW',
  },
]
